export { default as HomePage } from './page.home'
export { default as LoginPage } from './page.login'
export { default as RegisterPage } from './page.register'
export { default as PasswordPage } from './page.password'
export { default as PlayerPage } from './page.player'
